services:
    judge_server:
        image: littleorange666/judge_server:1.5.0
        read_only: true
        restart: always
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - ./sandbox:/sandbox
            - ./langs:/langs:ro
        environment:
            - SERVICE_URL=http://judge-server:9132
        ports:
            - "0.0.0.0:9132:8000"
