services:
    judge_redis:
        image: redis:4.0-alpine
        restart: always
        volumes:
            - ./data/redis:/data
    judge_postgres:
        image: postgres:15-alpine
        restart: always
        volumes:
           - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=orangejudge
            - POSTGRES_USER=orangejudgeuser
            - POSTGRES_PASSWORD=orangejudgepassword
        ports:
            - "0.0.0.0:5432:5432"
    judge_server:
        image: littleorange666/judge_server:1.3.0
        read_only: true
        restart: always
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - ./sandbox:/sandbox
            - ./langs:/langs:ro
        environment:
            - SERVICE_URL=http://judge-server:9132
        ports:
            - "0.0.0.0:9132:8000"
