services:
    judge_server:
        image: littleorange666/judge_server:1.1.1
        read_only: true
        restart: always
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - sandbox:/sandbox
        environment:
            - SERVICE_URL=http://judge-server:9132
        ports:
            - "0.0.0.0:9132:8000"
    judge_backend:
        image: orange_judge
        read_only: true
        restart: always
        user: "0:0"
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - sandbox:/app/sandbox
            - $PWD/data:/app/data
        environment:
            - JUDGER_URL=http://judge_server:8000
            - CONFIG_SERVER_PORT=8080
        ports:
            - "0.0.0.0:8080:8080"
        entrypoint: ["/app/entrypoint.sh"]
volumes:
    sandbox:
        external: false
        driver_opts:
            o: "nocopy"