smtp:
  enabled: false
  host: smtp.gmail.com
  port: 587
  user: user@gmail.com
  password: password

server:
  port: 8080
  workers: 4
  timeout: 120
  limits:
    - 20 per 30 second
    - 2 per 1 second

judge:
  workers: 1
  limit: 1 per 10 second
  file_size: 10

debug:
  log: false

account:
  signup: true
